name: Build container update
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build swu image
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
          repository: atmark-techno/mkswu
          path: mkswu
          ref: next
    - name: Install dependencies
      run: |
          # podman and cpio are already present
          sudo apt-get update
          sudo apt-get install -y zstd
    - name: Build container
      run: |
          podman build -t image:latest ./image
          podman save -o image.tar image:latest
    - name: Build swu
      run: |
          ./mkswu/mkswu --config-dir mkswu.conf.d container.desc
      env:
          SWUPDATE_KEY: ${{ secrets.SWUPDATE_KEY }}
          SWUPDATE_AES_KEY: ${{ secrets.SWUPDATE_AES_KEY }}
          MKSWU_PRIVKEY_PASS: ${{ secrets.SWUPDATE_KEY_PASS }}
    - name: Deploy
      uses: softprops/action-gh-release@v1
      with:
          tag_name: latest
          files: container.swu
